### ISSUE TITLE
Problem fetching the user profile

### ISSUE THREAD

**Issue by adriatic** [aurelia-auth0/new-samples#19]
Problem: the **`getProfile`** in **[`auth0-service.js](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/02-User-Profile/src/auth0-service.js)** class crashes with 
```
ERROR [app-router] Error: Error invoking Profile. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot read property 'rootUrl' of undefined
Inner Error Stack:
TypeError: Cannot read property 'rootUrl' of undefined
    at ./node_modules/auth0-js/src/authentication/index.js.Authentication.userInfo (http://localhost:8080/app.93b7bc8a7f9976e85859.bundle.js:18919:34)
    at Auth0Service.getProfile (http://localhost:8080/app.93b7bc8a7f9976e85859.bundle.js:51932:7)
    at new Profile (http://localhost:8080/app.93b7bc8a7f9976e85859.bundle.js:57446:41)
    at Object.invoke (http://localhost:8080/app.93b7bc8a7f9976e85859.bundle.js:6538:12)
    at InvocationHandler.invoke (http://localhost:8080/app.93b7bc8a7f9976e85859.bundle.js:6502:166)
```

The problem is in the line following code (` @callback userInfoCallback`)
```
/**
 * Makes a call to the `/userinfo` endpoint and returns the user profile
 *
 * @method userInfo
 * @param {String} accessToken token issued to a user after Auth
 * @param {userInfoCallback} cb
 * @see   {@link https://auth0.com/docs/api/authentication#get-user-info}
 */
Authentication.prototype.userInfo = function(accessToken, cb) {
  var url;

  assert.check(accessToken, { type: 'string', message: 'accessToken parameter is not valid' });
  assert.check(cb, { type: 'function', message: 'cb parameter is not valid' });

  url = urljoin(this.baseOptions.rootUrl, 'userinfo');

  return this.request
    .get(url)
    .set('Authorization', 'Bearer ' + accessToken)
    .end(responseHandler(cb, { ignoreCasing: true }));
};
```
at the line **` url = urljoin(this.baseOptions.rootUrl, 'userinfo');`**, where `this.baseOptions` is undefined, as indicated below:

![image](https://user-images.githubusercontent.com/2712405/40455517-44beb430-5ebb-11e8-8e98-e65c3cde5fdb.png)

**Note:** I do not believe that I found a bug in Auth0 SDK - it is a lot more likely that my setup is incorrect / incomplete.

Since I expect that you will review all of my code before being published (and I will also ask a few Aurelia guys to review the Aurelia specific code), so we do not end up being both embarrassed 😄, I hope that you will not mind making a clone of the **[new-samples](https://github.com/aurelia-auth0/new-samples)** repo, and run this **[02-User-Profile](https://github.com/aurelia-auth0/new-samples/tree/master/esnext-webpack/02-User-Profile) sample to find out what is missing.

Here is how you run this:
```
npm install
nps
```
where **[`nps`](https://www.npmjs.com/package/nps)** is a very useful npm utility that you ought to have even outside this task of bailing me out.

Once the app starts up, authenticate yourself:

![image](https://user-images.githubusercontent.com/2712405/40455807-83e72394-5ebc-11e8-9f91-352250f357c4.png)

once you are logged in, click on the Profile menu item:

![image](https://user-images.githubusercontent.com/2712405/40455868-bf9b6792-5ebc-11e8-8972-952ef14ccb6c.png)

and observe the crash in Chrome console:

![image](https://user-images.githubusercontent.com/2712405/40455921-f780164e-5ebc-11e8-885d-203ff6e5d6bb.png)

**Comment by adriatic** [comment]
After changing the code as Andres proposed in https://auth0.slack.com/archives/DAUD1CBFY/p1527126672000245:

```
getProfile() {
    let userProfile;
    let token = this.getAccessToken();
    if (token) {
      this.auth.client.userInfo(token, function (err, profile) {
        if (profile) {
          userProfile = profile;
        }
      })
    }
    return this.userProfile;
  }
```
The app does not crash in Auth0 SDK code - but I still do not get the profile:

![image](https://user-images.githubusercontent.com/2712405/40462114-8f792548-5edc-11e8-87dd-abd14d45fdda.png)

The token is correct but the code 

```
      this.auth.client.userInfo(token, function (err, profile) {
        if (profile) {
          userProfile = profile;
        }
```
fails. That indeed was my initial problem, before splitting the ` this.auth.client.userInfo(token, function (err, profile) {` in two statements

**Comment by adriatic** [comment]
Changing the above code into this:

```
  getProfile() {
    let userProfile;
    let token = this.getAccessToken();
    if (token) {
      this.auth.client.userInfo(token, function (err, profile) {
        if (err) {
          console.log("getProfile failed" + err)
          userProfile = null;
        } else {
          userProfile = profile;
        }
      })
    }
    return userProfile;
  }
```

**Comment by adriatic** [comment]
Easy fix for this situation - method **[`getprofile`](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/02-User-Profile/src/auth0-service.js#L77-L91)** needs to return the ___promise___ - not the profile itself

**Comment by adriatic** [comment]
Pilot error - simply forgot that the getProfile method needs to return the promise - not the profile 😢
