### ISSUE TITLE
Calling an API sample - UnauthorizedError: jwt malformed

### ISSUE THREAD

**Issue by adriatic** [aurelia-auth0/new-samples#21]
As suggested by @aaguiarz, I took the **[server.js](https://github.com/auth0-samples/auth0-express-api-samples/blob/master/01-Authorization-RS256/server.js)** code from the **[auth0-express-api-samples](https://github.com/auth0-samples/auth0-express-api-samples/tree/master/01-Authorization-RS256)**  to implement the code for the new Aurelia **[03-Calling-an-API](https://github.com/aurelia-auth0/new-samples/tree/master/esnext-webpack/03-Calling-an-API)** sample app. 

While the Public Ping to server works just fine:

![image](https://user-images.githubusercontent.com/2712405/40929282-49c89866-67f2-11e8-9890-5b8473ab5a61.png)

the Private Ping fails - the server rejects the the  **`XMLHttpRequest`** issued request which the client issues here:
```
callServer(endPoint, secured) {
    let url = this.apiUrl + endPoint;
    let xhr = new XMLHttpRequest();

    xhr.open('GET', url);
    if (secured) {
      let token = localStorage.getItem('access_token');
      xhr.setRequestHeader(
        'Authorization',
        'Bearer ' + token
      );
    }
    xhr.onload = function() {
      if (xhr.status == 200) {
        // update message
        requestStatus.innerText = JSON.parse(
          xhr.responseText
        ).message;
      } else {
        alert('Request failed: ' + xhr.statusText);
      }
    };
    xhr.send();     <-----
  }
```

### How to run:

- Start the **[back-end](https://github.com/aurelia-auth0/new-samples/tree/master/esnext-webpack/03-Calling-an-API/back-end)** app with the command **`npm start`**

- Start the **[front-end](https://github.com/aurelia-auth0/new-samples/tree/master/esnext-webpack/03-Calling-an-API/front-end)** app using the command **`nps`** (in a different terminal window)

- Click on the **`Log In`** button to get authenticated.

You should see this failure:

![image](https://user-images.githubusercontent.com/2712405/40930407-9c845966-67f5-11e8-9379-c0acd7ddf516.png)

**Comment by adriatic** [comment]
My guess: the **[client code](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/03-Calling-an-API/front-end/src/call-api.js#L12-L35)** is not compatible with the **[server code](https://github.com/aurelia-auth0/new-samples/blob/master/esnext-webpack/03-Calling-an-API/back-end/server.js)**.

I debugged through the service side just enough to see that the error:
```
Listening on http://localhost:3010
UnauthorizedError: jwt malformed
    at C:\work\aurelia-auth0\new-samples\esnext-webpack\03-Calling-an-API\back-end\node_modules\express-jwt\lib\index.js:102:22
    at Object.module.exports [as verify] (C:\work\aurelia-auth0\new-samples\esnext-webpack\03-Calling-an-API\back-end\node_modules\jsonwebtoken\verify.js:49:12)
    at verifyToken (C:\work\aurelia-auth0\new-samples\esnext-webpack\03-Calling-an-API\back-end\node_modules\express-jwt\lib\index.js:100:13)
    at fn (C:\work\aurelia-auth0\new-samples\esnext-webpack\03-Calling-an-API\back-end\node_modules\async\lib\async.js:746:34)
```
is generated in `jsonwebtoken\verify.js:49:12)`

![image](https://user-images.githubusercontent.com/2712405/40930804-bca24e14-67f6-11e8-81a5-217d266ed792.png)

**Comment by adriatic** [comment]
Such situation would arose from the fact that the client issues the following construct to authenticate itself:
```
  let url = this.apiUrl + endPoint;
    let xhr = new XMLHttpRequest();

    xhr.open('GET', url);
    if (secured) {
      let token = localStorage.getItem('access_token');
      xhr.setRequestHeader(
        'Authorization',
        'Bearer ' + token
      );
    }
```

**Comment by adriatic** [comment]
@aaguiarz found the problem - the **`audience`** string (item in the red rectangle)

![image](https://user-images.githubusercontent.com/2712405/40993668-2afe8aae-68c8-11e8-96ee-4013c229196b.png)

was spelled at one place as **`https://aa-demo-api-endpoint`** and at the other as **`https://aa_demo-api-endpoint`** (_note the difference between underscore and hyphen_).
